INSERT INTO PIZZA_TOPPING(NAME, RATE) VALUES('Sauce', 0);
INSERT INTO PIZZA_TOPPING(NAME, RATE) VALUES('Cheese', 0);
INSERT INTO PIZZA_TOPPING(NAME, RATE) VALUES('Onion', 1);
INSERT INTO PIZZA_TOPPING(NAME, RATE) VALUES('Pepper',1);
INSERT INTO PIZZA_TOPPING(NAME, RATE) VALUES('Chicken', 1);
INSERT INTO PIZZA_TOPPING(NAME, RATE) VALUES('Meat', 1);
INSERT INTO PIZZA_TOPPING(NAME, RATE) VALUES('olives', 1);
